/***************************************************************************
 *   KEYDEFS.H      - defines for configurable keys                        *
 *                                                                         *
 *                                                          Les 07/22/95   *
 ***************************************************************************/

#define   KEYFWD         0
#define   KEYBACK        1
#define   KEYLEFT        2
#define   KEYRIGHT       3
#define   KEYRUN         4
#define   KEYSTRAFE      5
#define   KEYFIRE        6
#define   KEYUSE         7
#define   KEYJUMP        8
#define   KEYCROUCH      9
#define   KEYLKUP        10
#define   KEYLKDN        11
#define   KEYCNTR        12
#define   KEYSTFL        13
#define   KEYSTFR        14
#define   KEYMAP         15
#define   KEYZOOMI       16
#define   KEYZOOMO       17
#define   MAXKEYS        18

